### ISSUE TITLE
Use only one founction for all the slaiders !

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#1]
Oui je mets des issues....c'est gonfle :)

Un truc qui serait super classe et super style, c'est d'avoir la meme function pour tous les sliders.. la fonction, le truc ce serait que la fonction chope en argument l'extent et le nom de la dimension o`u le slide a ete effectue.. du coup tu aurais plus qu'une seule function pour tous les glisseurs.. magique !

**Comment by charlottegiseleweil** [comment]
Ahah yeah mets des issues j'adore :)

Elle te plait pas ma fonction sliders_plot() ? ;) Merci pr la suggestion, je mets dans ma todo list mais honnêtement pour l'instant j'ai déjà tant de fonctionnalités à implémenter que je suis dans la "good enough" zone...! In challah si j'ai le time après ! (Et Happy niou ïeurre !)
