### ISSUE TITLE
Si on bouge les trucs tres vite sur le paarcords, les scatterplots ont pas les bonnes datas

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#10]
1 - Il y a effectivement un truc avec les extremums

2- Il y a un truc bizarre avec les scatterplots..

**Comment by chabb** [comment]
Grr... un jour je remettrais les transitions :) mais pas maintenant...

**Comment by charlottegiseleweil** [comment]
Ahah oui le coup du "très vite" ça doit pas bien se marier avec les
transitions ;)

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

2017-02-04 14:03 GMT-08:00 Chabbey François <notifications@github.com>:
