### ISSUE TITLE
Le squatteur ne pelote plus..

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#11]
How to repro : 
1) Play with the parcoords, scatterplot is updated
2) Open the table, hover on the table
3) Play with parcoords, scatterplot is not updated

Sadness is infinite

**Comment by charlottegiseleweil** [comment]
Hey how do you add explanation text to your commits ? ;)

**Comment by charlottegiseleweil** [comment]
pire que ça :dès e parcoords est brushé, le scatterplot ne se highlight plus :(

Donc parcoords.brush + table --> nique le scatterplot :(
