### ISSUE TITLE
Sliders interval is [ [ we want them [ ]

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#13]
interval is prob ][ and should be [] oooops

**Comment by chabb** [comment]
i think interval is [ [  (if we speak of crosffilter)

**Comment by charlottegiseleweil** [comment]
Ouep ! faut que je fix ça !

**Comment by charlottegiseleweil** [comment]
Actually yes, test done interval is : [ [

**Comment by charlottegiseleweil** [comment]
or even sometimes ][ !!

**Comment by charlottegiseleweil** [comment]
oh yeah !
