### ISSUE TITLE
pu sliders grab left branch

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#14]
bugbugbug

**Comment by chabb** [comment]
mais.. c'est quoi le bug ?

**Comment by charlottegiseleweil** [comment]
je pense que c'est une bite du CSS. SOmetimes tu peux pas grabber le sliders gauche des sliders roses. Faut que je fix ça aussi mais don't worry je me mets toutes ces issues quand je trouve des bugs pour les fixer à l'avenir !
