### ISSUE TITLE
Dataset table doesn't shrink to reflect subset upon slide of sliders

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#17]

**Comment by charlottegiseleweil** [comment]
fixed !!! Woohoo @ufenegga regarde moi ça comme j'suis trop forte :)
En fait les définitions (de update table upon brush etc)étaient un peu bancales

**Comment by chabb** [comment]
@charlottegiseleweil  i am so proud of your commits (; non mais sans rire donc... :) <= smiley-parentheses, un nouveau concept
