### ISSUE TITLE
Brushing parcoords THEN sliders (on gh-pages branch) (and merging branches?)

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#2]
Alors, je suis pas une pro de github, donc pas trop sûre de comment mergé les changements sans risquer de tout exploser mais petit remarqué petit truc qui bug avec la version gh-pages (i.e celle qu'on a finit ensemble au hipster-breakfast et qui est [là](https://charlottegiseleweil.github.io/webviz_natcap/) : 

**Quand on brush les axes de parcoords, puis qu'on brush les sliders, les brushs des sliders se s'additionnent pas (tu vois ce que je veux dire ?)**

Peut-être est-ce fixé dans la version BetterWay mais j'ai peur que si je merge je perdes tout gh-pages ! 0_0

Accessoirement on pourrait les merger tu crois? J'ai pushé les chgmts du hipster-breakfast etc sur gh-pages :)

**Comment by chabb** [comment]
oh my God, des caracteres gras **en gras.**. ca mets une pression de ouf  :)  je crois que j'ai corrige ce comportement intolerable des slaiders et du brushing

je pense qu'on peut merger sans trop de soucis ce truc, mais il va y avoir des flonkis et tout... c'est interessant les conflits pour apprendre GIT mais c'est un peu flippant la premiere fois

```  perso , mon premier conflit, je l'ai tres mal gere :) ```

je te propose,de verifier le behaviour de la branche betterWay, pour voir si c'est bien ce que tu veux : 
genre tu fais 
```
git fetch
git checkout --track origin/betterWay
```

et apres tu lances le serveur local

pour revenir a la branche initiale tu fais 

```
git checkout gh-pages
```
ah ah j'adore mettre du code comme ca, ca fait trop genre 😄 

si ca te parait bien, tu peux essayer de merger pour voire ce qui va se passer.. ca risque rien.. tout de facon on peut toujours revenir en arriere avec GIT, meme si tu petes tout ( on a les differents commits, et GIT stocke les 20 dernieres operations d'ecriture).. si c'est la merguez pour merger, je peux faire le merge...

redis-moi si tu as un souci

il a le style ton avatar 📷

**Comment by charlottegiseleweil** [comment]
Allez je vais tenter des folies alors ! 😃 Merci !

**Comment by chabb** [comment]
Good luc !

Pour Git, si t'as du temps a perdre :  http://learngitbranching.js.org/...  
c-est un tuto interactif avec des exercices qui est bien ( 1 heure)

**Comment by charlottegiseleweil** [comment]
Ah ba voilà, je vais faire ça avant de tout bidouiller j'ai un peu peur de
tout perdre avec ces conneries ahah

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

Le 3 janvier 2017 à 11:55, Chabbey François <notifications@github.com> a
écrit :
