### ISSUE TITLE
Rendre la map zoomable 

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#25]
Faut faire des trucs cool aussi :)

**Comment by charlottegiseleweil** [comment]
Grave ! La map zoomable & la page d'accueil avec les trois watersheds dans leur context (superposés à un leaflet or so) j'arrive pas à retrouver le bl.ocks que t'avais fait dans ce genre ?

**Comment by chabb** [comment]
C'est que je l'ai pas mis dans un bl.ocks.org... l'exemple est bien au chaud dans mon disque dur... mais il est tout crade et vilain, j'ai honte de le partager... je veux juste le fixer avant
