### ISSUE TITLE
Bug table + brush order (maybe just review function table/update)

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#26]
Reproduce: 
1 Brush parcoords
2 Then open table
3 Hover: scatterplot doesn't highlight

**Comment by chabb** [comment]
C'est parce que quand tu cliques sur le bouton tu passes l'objet full_data a la table.. 
le probleme c'est que si on a filtre, il faut passer filtered_data.. . 
le trick c'est de definir ``` filtered_data = full_data ``` au lancement de l'app

**Comment by chabb** [comment]
PS : si tu veux garder toutes les datas dans la table, dans ce cas la, c'est normal que le scatterplot
ne highlight pas parce qu'il a pas tous les 'points' de la table
