### ISSUE TITLE
bug: quand overlay checked, noms des radiobuttons don't update upon toggle

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#28]

**Comment by charlottegiseleweil** [comment]
Solved. However:
1. quand overlay checked (toggle: portfolio)
2. toggle: obj
3. toggle back to portfolio
4. overlay still checked but doesn't show :(

**Comment by chabb** [comment]
It's because you put class 'invisblee' when you toggle to 'obj' .. when you toggle back to 'portfolio', you have to check the state of the checkbox, if it's checked, we need to put back the overlay

**Comment by charlottegiseleweil** [comment]
Mais quand tu dis closed c'est que tu l'as fait ou je le fais ? (Parce que
je le vois pas dans les commits si jamais tu l'as fait)

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

2017-02-18 13:28 GMT-08:00 Chabbey François <notifications@github.com>:
