### ISSUE TITLE
Zoom: change button to "Enable Zooming"/Reset zoom

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#29]
Parce que c'est chiatn sinon ça zoome tout seul

**Comment by chabb** [comment]
Une fois que le zoom est enabled, on ne peut plus revenir en arrier ( genre le des-enabled)

**Comment by charlottegiseleweil** [comment]
je sais, ba c'est pas grave ;)

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

2017-02-11 21:46 GMT-08:00 Chabbey François <notifications@github.com>:
