### ISSUE TITLE
Layout ! (see branch map)

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#3]
Carré vert: supposed to be parcoords+sliders: can't get them both inline. + the sliders seem to wanna go in the map canvas

Carré rouge: supposed to be map_canvas, but the map seems to want her own canvas...

**Comment by chabb** [comment]
Carre vert : c'est parce que, commiter des fichiers, oublier tu as ! Dans la console, du rouge il y a ! ( et du coup tous les voyants sont au rouge... et tu vois rouge dans le carre vert )

Carre rouge: Tu as mis du float, sache que tu  ne pourras utiliser le float qu'a partir de **42367,401** points d'experience ! ( bon peut=etre kil trainait dans le CSS et que c'est pas tou qui l'a mis... jai eu la flemme de verifier ). Si on oublie le float, ca marche non plus plas,  le souci vient de 2 trucs :
- oubli d'un inline-block
- le body avait une width de 1000 px, or la largeur cumulee des deux div contenues fait (960 + 410) = 1370px...  du coup le navigateur renvoie la deuxieme div a la ligne suivante

En fait tu manques d'experience avec les tools CSS de chrome j'aurais du te montre ca, c'est le sabre-laser du Jedi CSS .. tel Obi-Wan Kenobi, j;ai failli a ta formation de Padawan et le monde s'en trouve menace..

Bon du coup j;ai pousse un commit avec les corrections pour le carre rouge avec des grosses bordures et des couleurs pour que tu voies bien le truc, mais faut se preparer psychologiquement parce que les couleurs que j'ai utilise risque de te faire peter les vaisseaux des yeux et ca me la foutrait mal si tu deviens aveugle suite a cette agression visuelle.

Ah.. les styles user-agent, c'est les styles par defaut du navigateur... 
 ( exemple: une div a un display:block par defaut, du coup ca apparait dans les dev-tools)

Bonne nuit bisous !!

**Comment by charlottegiseleweil** [comment]
Mais mais mais 

Commiter des fichiers: j'ai pas oublié, git status me dit que je suis grave up to date de la life ! (?!)

Et tout ça ça me dit toujours pas pourquoi la map elle veut pas tranquillement se squeezer dans le carré vert COMME TOULMONDE !

**Comment by charlottegiseleweil** [comment]
1/ .slider class doesn't work because les changements sont overwritten by des trucs de css de bootstrap

2/ La map j'arrive pas à la réduire, si je réduis la width ça la coupe au lieu de l'afficher plus petite.

3/ j'ai des soucis de inline-block/block ahah mais clairement on en parlera en live (en gros quand je fais map-stuffs un div réunissant toggle button+legend, pour mettre tout ça in-line-block avec la map, ils s'affichent plus bas c'est étraaaaange !)
