### ISSUE TITLE
Sortir le javascript de intro.html. Mettre les autres watersheds

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#30]
Une mission de fou top secrete...

**Comment by charlottegiseleweil** [comment]
![capture d ecran 2017-02-12 a 21 58 05](https://cloud.githubusercontent.com/assets/18381609/22872490/7138a8e2-f16e-11e6-9ff2-a80afa7630c2.png)

Ca devrait donner un truc comme ça (rose = s; bordeaux=tc; bleu=m).

Coordonnées: (format : West Nord Est Sud, j'ai pris une petite marge)
s :  37.31485    -0.16380    36.60179       -0.63174
tc : 36.57871    -0.62339    37.07796       -1.04606
m: 36.70657    -0.63466     37.26312      -0.82007

**Comment by chabb** [comment]
Ok.. j'ai pu afficher les trois rasters.. maintenant il y a une anicroche.. 

En resume, ces rasters sont super lourds, donc super precis, on peut zoomer et tout, et changer les couleurs.. Mais du coup, si on veut les afficher les 3 en meme temps, la masse de calcul bloque le thread principal du JS ( = truc pas cool, le navigateur devient tout lent tel une limace flemmarde..)

Plusieurs solutions: au lieu de raster, faire des images toutes pretes, comme ca on a qu'a les afficher et ce sera super simple ( par contre on pourra plus changer les couleurs a la volee.. -en fait on peut, mais c'est pas bien-  ). L'autre solution, c'est de deporter les calculs sur un WebWorker, comme ca on ne bloque pas le thread principal ( plus complique )

Par rapport aux 3 cartes, il me semble qu'elles sont un peu trop decalees en direction du NE ( les contours matchent pas avec des contours qui correspondent sur les tiles de la map )

**Comment by charlottegiseleweil** [comment]
En fait, si on avait les 3 watersheds compressés (agreggés par 4 pixels) comme on a toutes les autres maps, ça marcherait ? Il seraient grave moins lourds.

Sinon images et fixer la couleur marche tb aussi même si, à terme, c'est moins générique

**Comment by chabb** [comment]
oui, je pense que ca devrait le faire, tu peux les choper pour demain ?

**Comment by charlottegiseleweil** [comment]
Ok doing my best !

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

2017-02-15 12:41 GMT-08:00 Chabbey François <notifications@github.com>:

**Comment by chabb** [comment]
Mettre du texte, faire un layout.. etc etc...

**Comment by charlottegiseleweil** [comment]
Je m'occupe du texte et cherche un layout cette semaine ! Je peux aussi sortir le js du html :) Will do soon
