### ISSUE TITLE
Fancy alerts SweetAlert2 Library marche pas :'(

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#31]
<script src="bower_components/es6-promise/es6-promise.auto.min.js"></script>
 <script src="bower_components/sweetalert2/dist/sweetalert2.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.4.1/sweetalert2.common.min.js"></script>
 <link rel="stylesheet" href="bower_components/sweetalert2/dist/sweetalert2.min.css">

**Comment by charlottegiseleweil** [comment]
Bon actually ça marche mais 
1. Why when I put all BtnHelp-related explanations in a separate script (that I link in index of course) it doesn't work ? (ce serait plus propre que de mettre tous les textes dans main)
2. Je suis censée pouvoir mettre des liens dans le html, haven't figure it our yet.

**Comment by charlottegiseleweil** [comment]
3. figure out comment aller à a ligne aussi.

**Comment by charlottegiseleweil** [comment]
Todo also : the right texts/explanations once I figure out the html for fancy alerts :)

**Comment by chabb** [comment]
http://codepen.io/chab/pen/rjRPYo pour le retour a la ligne
