### ISSUE TITLE
Tester l'oeuvre sur Safari, Firefox, IE 11

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#32]
Tel le peintre delaissant la peinture a l'huile pour l'aquarelle ou la gouache, l'aspirant Picasso du developpement Wouebe se doit de tester sa webapp sur des navigateurs moins shiny et plus rugueux, tel Safari et Firefox. Je ne te propose PAS de tester sur IE 11, tu vas vouloir rentrer en Europe apres :)

**Comment by charlottegiseleweil** [comment]
Test successful on Firefox

Fail on Safari, mais qu'y faire? Maybe un message initial si on voit que l'user est sur Safari "Hey use Chrome ! " 

Reste à tester sur PC, different screen sizes etc, je vais faire ça prochainement.

**Comment by chabb** [comment]
ben faut regarder le CSS et faire un sorte que ca marche :) Safari fait des trucs bizarres des fois, pour IE>11, si ca marche sur Chrome/Ffox, ca devrait marcher..

**Comment by charlottegiseleweil** [comment]
y'a une fonction qui detecte que l'utilisateur utilise Safari ?
In that case I'd rather just do a pop up window qui leur dit d'aller sur
Firefox ou Chrome ! :)

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

Le 15 février 2017 à 12:39, Chabbey François <notifications@github.com> a
écrit :

**Comment by chabb** [comment]
faut regarder l'user-agent ou faire du feature-sniffing

peut-etre :
```var isSafari = /constructor/i.test(window.HTMLElement) || (function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || safari.pushNotification);```


mais j;essaierais de fixer le CSS, ca devrait pas etre trop complique

**Comment by chabb** [comment]
en fait ca bug, parce que Safari n'a pas createImageBitmap dans son API... donc je pense qu'il faudrait essayer de passer un tableau type, comme suggere ci-dessous... ou dessiner l'image dans un 'stencil canvas' et l;exporter en image mais c'est lourdingue

pour safari : http://stackoverflow.com/questions/40094245/createimagebitmap-alternative-on-safari

**Comment by charlottegiseleweil** [comment]
Mais on a pas juste une fonction qui peut nous dire si l'user est sur safari et, le cas échéant, on lui fout un lien pr download Chrome ou Firefox ? :)
