### ISSUE TITLE
L'ami Peter et ses maps

### ISSUE THREAD

**Issue by chabb** [charlottegiseleweil/webviz_natcap#4]
Yo.. je me demandais comment Peter il faisait avec ses maps.. donc j'ai jete un coup d'oeil rapide.. en fait il s'est pas trop triture les neurones, il il a fait des images fixes en .PNG ( rien a voir avec les habitants de la banquise), parce que lui, ca l'interessait pas de mettre ses images sur des maps avec des tiles, donc des images toutes simples ca lui suffisait.
En gros toi tu as des rasters bien heavy-metal qui pesent 4 MB, parce qu'ils ont TOUTES les infos pour chaque pixel. 
Si on les transforme en .PNG, on a un format qui est optimise pour l'affichage, et donc bien plus leger et rapide ( genre les maps a piterre, elles font 10 Ko donc c'est un brin lighter... )
, le hic, c'est que on perd toute possibilite de traitement dessus, en terme de traitement pixel par pixel (pas tout a fait vrai mais pour faire simple je vous prie d'accepter mes propos :) )..
Par contre on peut toujours appliquer une matrice de transformation a l'image je pense (en language comprehensible = on peut toujours reprojeter l'image sur une tile)

En fait tu peux meme empiler les images les unes sur les autres en jouant avec l'opacite pour voir ce qui se passe si tu cumules des scenario, un peu comme les spaggethis-bolos plots ( ou pas ...)

je me suis permis, que dis-je, j'ai eu l'outrecuidance, de penser que ce genre de basses considerations techniques pouvaient peut-etre figurer dans ton report...

Have a nice day

**Comment by charlottegiseleweil** [comment]
Oui oui je sais ! Pardon j'aurai pu te dire ça, il a pré-loadé toutes les
maps, mais je croyais bien de l'avoir dit, il les as toutes générées avant,
et les calculs sont donc plus à faire !!

Charlotte Weil
Visiting student researcher at Stanford University
Master student at École Polytechnique de Lausanne
*_________________________________________*
« Be the change you wish to see in the world »   [Mahatma Gandhi]

Le 25 janvier 2017 à 10:14, Chabbey François <notifications@github.com> a
écrit :

**Comment by chabb** [comment]
apres avoir fouille dans mes archives, je crois bien que tu me l'as dit, mais si tu veux c'est rester dans un coin du cerveau, du coup je l'avais pas mis dans le contexte...
