### ISSUE TITLE
SINGLE SOLUTION OBJ MAP DISPLAY BREAKS

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#54]
AU SECOURS WHY WHY WHY WHY

On a local host: ça show le pie plot puis break
Online : ça break

Oh @ufenegga
Au secours, plize aide moi
Haiku hopla !

**Comment by chabb** [comment]
Ta ta ta, and the problem was : 
an ugly infinite loop that cause a black hole and breaks everything, see the c60c0e6 

Actually i am bit surprise that there is only one value in the extent but that is another story
