### ISSUE TITLE
Questions gnrls

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#7]
Pas sûre d'avoir super bien compris le "dots.exit().remove();" (scatterplot.js line 78)
Parce que lorsque j'enlève cette ligne, certains dots disparaissent quand même upon brushing...

**Comment by chabb** [comment]
Je vais tenter une explication.. attention ( on va parler du concept d'object constancy)   : 

Essayons de passer en terme de code, mais de rester high-level ( i am flying high :) ).  

1. Disons que tu as ces datas [{x:10,y:10}, {x:20, y:20}, {x:30, y:30} ], et que tu utilises D3 pour
dessiner un scatterpellotedelaine. Tu vas avoir 3 cercles au coordonees (10,10) (20,20) (30,30).
Appelons les C1 C2 C3 

2. Maintenant supposons qu'on a des nouvelles datas [{x:10,y:10}, {x:20, y:20}, {x:40, y:40} ]
D3 ne va pas creer des nouveaux cercles, mais va juste changer les cordonnes de C3, qui sera a (40, 40)

3. Maintenant supposons qu'on a plus que [{x:40, y:40}], intuitivement tu vois que ca correspond au troisieme cercle, et qu'on a du enlever les deux autres.. mais pas pour D3..  La question a se poser est la suivante (je mets des gros caracteres c'est important). COMMENT D3 FAIT POUR SAVOIR A QUELLES CERCLES CORRESPOND QUELLES DATAS ? hein, comment il fait ?

Il va regarder l'index de la data dans le tableau que tu lui passes. donc si on reprend ce tableau
[{x:40, y:40}] .. D3 va se dire, ah ah j'ai 3 cercles dans ma page, mais plus qu'un element dans le tableau. Comme cet element est le premier element, il va se dire :  
- Je dois updater C1 a (40,40) 
- Je dois enlever C2 et C3 vu qu'il sont plus dans le tableau 
du coup tu vas avoir un truc bizarre, certains cercles vont disparaitre et d'autre vont prendre leur place.......

Ce qu'il faut, c'est de filer a D3 une fonction qui permet de faire le mapping entre tes datas et les cercles affiches; c'est la notion de 'clef', chaque data a une clef qui permet a D3 de faire le lien entre la data pure ( la data dans le tableau), et ce qui est affiche sur la page. Par defaut, cette fonction est l;index de la data dans le tableau que tu passes a D3. 

Ca c'est le conceptuel...

**Comment by charlottegiseleweil** [comment]
Merci pour ces explications... Je crois comprendre mais ne vois pas exactement comment linker ça à notre tableau... Enfin on peut en parler en vrai vendredi :p :) Ci-mer !

**Comment by chabb** [comment]
C'est pour ca qu'il ne faut pas enlever la colonne index dans le CSV ( ou je sais plus comment elle s'appelle)  car c'est la seule clef qu'on a pour identifier une donnee.. more on that friday
