### ISSUE TITLE
Check that the stuff zorks zith the extremums

### ISSUE THREAD

**Issue by charlottegiseleweil** [charlottegiseleweil/webviz_natcap#9]

**Comment by chabb** [comment]
En fait c'etait a cause des animations, et la tu vas dire "oui tu vois que tes animations non-academiques elles mettent le petchi" :) mais bon,  le bon cote, c'est que ce bug c'etait un truc mystique, si tu parviens a le comprendre, tu seras REALLY a d3 top-hackeuse of the eDg3 of Da d3 Wer7dZ
